#!/usr/bin/env bash
export P=$(pwd)
image1='registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift'
image2='registry.access.redhat.com/openshift3/jenkins-agent-maven-35-rhel7'
image3='maven:3.6.3-adoptopenjdk-8'
image4='registry.access.redhat.com/openjdk/openjdk-11-rhel7'

docker run -it --rm --name maven3 -v $P:/opt/src -w /opt/src  ${image2} bash

