SELECT r.reportDate as eventdate,
       r.code,
       r.doname,
       r.name_do,
       r.block,
       r.counterpartyName,
       r.counterpartyInn,
       r.inn_clean,
       r.name_clean,
       r.is_custom_contractor_dict,
       r.reportdate,
       r.approvalauthority,
       r.approvaldate,
       r.approvaldocumentdetails,
       r.expirationdate,
       r.collateral,
       r.collateralcomment,
       trim(r.limitcurrency) as limitcurrency,
       cast(r.limitincurrency as double) as limitincurrency,
       cast(r.limitinrub as double) as limitinrub,
       r.loaddate,
       r.modificationdate,
       cast(r.paymentdefermentdays as integer) as paymentdefermentdays,
       r.segment,
       r.filename,
       r.sheetname,
       r.error_status,
       r.ts_update,
       r.id_sha2
FROM {dbSchema}.collisions_report_credit_limit AS r
where r.in_black_list=false and r.in_white_list=true and r.is_corrupted_field=false and r.name_do is not null and code is not null
