SELECT res.*,
       sha2(concat(coalesce(res.name_do, 'null'),
                   coalesce(res.eventdate, 'null'),
                   coalesce(res.name, 'null'),
                   coalesce(res.norm_name, 'null'),
                   coalesce(res.inn, 'null'),
                   coalesce(res.status, 'null'),
                   coalesce(res.sparkInterfaxCreditLimit, 'null'),
                   coalesce(res.cautionIndex, 'null'),
                   coalesce(res.financialRiskIndex, 'null'),
                   coalesce(res.paymentDisciplineIndex, 'null'),
                   coalesce(res.riskFactors, 'null'),
                   coalesce(res.negativeRegistries, 'null'),
                   coalesce(res.pledges, 'null'),
                   coalesce(res.legalCasesCountTwoYears, 'null'),
                   coalesce(res.legalCasesClaimsSumTwoYears, 'null'),
                   coalesce(res.legalCasesDecisionsSumTwoYears, 'null'),
                   coalesce(res.news1, 'null'),
                   coalesce(res.news2, 'null'),
                   coalesce(res.news3, 'null'),
                   coalesce(res.news4, 'null'),
                   coalesce(res.isDishonestSupplier, 'null'),
                   coalesce(res.sheetname, 'null'),
                   coalesce(res.loaddate, 'null'),
                   coalesce(res.filename, 'null')
                ), 256) AS id_sha2
FROM (
         SELECT DISTINCT 'sort_do'            AS name_do,
--         udf_convert_to_local_date(loaddate) as eventdate,
                         udf_convert_to_local_date(
                                 translate(regexp_extract(filename, "\\d{4}\\.\\d{2}\\.\\d{2}", 0), ".", "-"))
                                              AS eventdate,
                         name,
                         udf_normalized(name) AS norm_name,
                         inn,
                         status,
                         sparkInterfaxCreditLimit,
                         cautionIndex,
                         financialRiskIndex,
                         paymentDisciplineIndex,
                         riskFactors,
                         negativeRegistries,
                         pledges,
                         legalCasesCountTwoYears,
                         legalCasesClaimsSumTwoYears,
                         legalCasesDecisionsSumTwoYears,
                         news1,
                         news2,
                         news3,
                         news4,
                         isDishonestSupplier,
                         sheetname,
                         loaddate,
                         modificationdate,
                         filename
         FROM {dbSchema}.spark_interfax_summary_sort_do
     ) res
