SELECT r.*, CASE WHEN r.code IS NULL THEN 'NOT_MAPPING' ELSE 'OK' END AS error_status
FROM (
         SELECT max(md_1.code) AS code,
                sp.id_sha2,
                sp.name_do,
                sp.eventdate,
                sp.name,
                sp.norm_name,
                sp.inn,
                sp.status,
                sp.sparkInterfaxCreditLimit,
                sp.cautionIndex,
                sp.financialRiskIndex,
                sp.paymentDisciplineIndex,
                sp.riskFactors,
                sp.negativeRegistries,
                sp.pledges,
                sp.legalCasesCountTwoYears,
                sp.legalCasesClaimsSumTwoYears,
                sp.legalCasesDecisionsSumTwoYears,
                sp.news1,
                sp.news2,
                sp.news3,
                sp.news4,
                sp.isDishonestSupplier,
                sp.sheetname,
                sp.loaddate,
                sp.modificationdate,
                sp.filename
         FROM {dbSchema}.union_spark_interfax_summary sp
             LEFT JOIN (SELECT DISTINCT code, inn_clean FROM {dbSchema}.md_contractor_dict WHERE inn_clean IS NOT NULL) md_1
         ON sp.inn = md_1.inn_clean
         GROUP BY
             sp.id_sha2,
             sp.name_do,
             sp.eventdate,
             sp.name,
             sp.norm_name,
             sp.inn,
             sp.status,
             sp.sparkInterfaxCreditLimit,
             sp.cautionIndex,
             sp.financialRiskIndex,
             sp.paymentDisciplineIndex,
             sp.riskFactors,
             sp.negativeRegistries,
             sp.pledges,
             sp.legalCasesCountTwoYears,
             sp.legalCasesClaimsSumTwoYears,
             sp.legalCasesDecisionsSumTwoYears,
             sp.news1,
             sp.news2,
             sp.news3,
             sp.news4,
             sp.isDishonestSupplier,
             sp.sheetname,
             sp.loaddate,
             sp.modificationdate,
             sp.filename
     ) r
