SELECT T.*,
    case
        when
            coalesce(custom.inn_clean, T.inn) is null
            or
            trim(coalesce(custom.inn_clean, T.inn))='-'
            or
            trim(coalesce(custom.inn_clean, T.inn))='0'
            or
            trim(coalesce(custom.inn_clean, T.inn))='(пусто)'
            then null
        else coalesce(custom.inn_clean, T.inn)
    end as inn_clean,
    coalesce(custom.name_clean_norm, udf_normalized(T.name)) as name_clean,
    CASE WHEN custom.inn_clean IS NOT NULL or custom.name_clean_norm is not null THEN true ELSE false END AS is_custom_contractor_dict
FROM
(
    SELECT res.*, sha2(concat(
             coalesce(res.filename,'null'),
             coalesce(res.name_do,'null'),
             coalesce(res.year,'null'),
             coalesce(res.name,'null'),
             coalesce(res.eventdate,'null'),
             coalesce(res.inn,'null'),
             coalesce(res.contractor_code,'null'),
             coalesce(res.member_of_special_group,'null'),
             coalesce(res.department,'null'),
             coalesce(res.industry,'null'),
             coalesce(res.slice_date_1,'null'),
             coalesce(res.slice_date_2,'null'),
             coalesce(res.contractor_class,'null'),
             coalesce(res.solvency_group,'null'),
             coalesce(res.points,'null'),
             coalesce(res.credit_limit,'null'),
             coalesce(res.limit_Estimation_RSBU,'null'),
             coalesce(res.fin_Metr_Coverage_Coefficient_Points,'null'),
             coalesce(res.fin_Metr_Hot_Liquidity_Coefficient_Points,'null'),
             coalesce(res.fin_Metr_Capital_Turnover_Points,'null'),
             coalesce(res.fin_Metr_Selling_Profitability_Points,'null'),
             coalesce(res.fin_Metr_Assets_Profitability_Points,'null'),
             coalesce(res.fin_Metr_Financial_Stability_Coefficient_Points,'null'),
             coalesce(res.bus_Rep_Cooperation_Experience_Category,'null'),
             coalesce(res.bus_Rep_Cooperation_Experience_Points,'null'),
             coalesce(res.bus_Rep_Payment_Discipline_Category,'null'),
             coalesce(res.bus_Rep_Payment_Discipline_Points,'null'),
             coalesce(res.calculation_Non_Current_Assets,'null'),
             coalesce(res.calculation_Net_Assets,'null'),
             coalesce(res.calculation_Current_Assets,'null'),
             coalesce(res.calculation_Current_Liabilities,'null'),
             coalesce(res.rsbu_financial_statements,'null'),
             coalesce(res.assets_Non_Current_Intangible_Assets,'null'),
             coalesce(res.assets_Non_Current_RND_Results,'null'),
             coalesce(res.assets_Non_Current_Non_Material_Research_Assets,'null'),
             coalesce(res.assets_Non_Current_Material_Research_Assets,'null'),
             coalesce(res.assets_Non_Current_Fixed_Assets,'null'),
             coalesce(res.assets_Non_Current_IBP_Into_Tangible_Assets,'null'),
             coalesce(res.assets_Non_Current_Financial_Investments,'null'),
             coalesce(res.assets_Non_Current_Deferred_Tax_Asset,'null'),
             coalesce(res.assets_Non_Current_Other_Assets,'null'),
             coalesce(res.assets_Current_Inventory,'null'),
             coalesce(res.assets_Current_VAT_On_Acquired_Valuables,'null'),
             coalesce(res.assets_Current_Receivables,'null'),
             coalesce(res.assets_Current_Long_Term_Receivables,'null'),
             coalesce(res.assets_Currentdebts_Of_Founders,'null'),
             coalesce(res.assets_Current_Financial_Investment,'null'),
             coalesce(res.assets_Current_Cash,'null'),
             coalesce(res.assets_Current_Other,'null'),
             coalesce(res.liability_Equity_Statutory_Capital,'null'),
             coalesce(res.liability_Equity_Own_Stock,'null'),
             coalesce(res.liability_Equity_Non_Current_Assets_Revaluation,'null'),
             coalesce(res.liability_Equity_Equity_Reserve,'null'),
             coalesce(res.liability_Equity_Retained_Earnings,'null'),
             coalesce(res.liability_Long_Term_Liabilities_Loans_And_Borrowings,'null'),
             coalesce(res.liability_Long_Term_Liabilities_Deferred_Tax_Liabilities,'null'),
             coalesce(res.liability_Long_Term_Liabilities_Estimated_Liabilities,'null'),
             coalesce(res.liability_Long_Term_Liabilities_Received_Advances_Payables,'null'),
             coalesce(res.liability_Long_Term_Liabilities_Other_Liabilities,'null'),
             coalesce(res.liability_Short_Term_Liabilities_Loans_And_Borrowings,'null'),
             coalesce(res.liability_Short_Term_Liabilities_Accounts_Payable,'null'),
             coalesce(res.liability_Short_Term_Liabilities_Deferred_Income,'null'),
             coalesce(res.liability_Short_Term_Liabilities_Estimated_Liabilities,'null'),
             coalesce(res.liability_Short_Term_Liabilities_Other_Liabilities,'null'),
             coalesce(res.pnl_Net_Revenue,'null'),
             coalesce(res.pnl_Operating_Profit,'null'),
             coalesce(res.pnl_Year_Net_Profit,'null'),
             coalesce(res.statement_Of_Changes_In_Equity_Net_Assets,'null'),
             coalesce(res.rsbu_financial_statements_currency,'null'),
             coalesce(res.assets_Current_Total, 'null'),
             coalesce(res.liability_Short_Term_Liabilities_Total, 'null'),
             coalesce(res.liability_Long_Term_Liabilities_Total, 'null'),
             coalesce(res.liability_Equity_Total, 'null'),
             coalesce(res.assets_Non_Current_Total, 'null'),
             coalesce(res.liabilities_Total, 'null'),
             coalesce(res.assets_Total, 'null'),
             coalesce(res.cover_Ratio, 'null'),
             coalesce(res.quick_Liquidity_Ratio, 'null'),
             coalesce(res.working_Capital_Turnover, 'null'),
             coalesce(res.financial_Stability_Index, 'null'),
             coalesce(res.margin_On_Sales, 'null'),
             coalesce(res.return_On_Assets, 'null')
         ), 256) as id_sha2
    FROM (
        select
            L.filename,
            L.name_do,
            L.year,
            L.name,
            udf_convert_to_local_date(coalesce(
                from_unixtime((unix_timestamp(L.slice_date_1, 'MM/dd/yy')),'yyyy-MM-dd'),
                from_unixtime((unix_timestamp(replace(L.slice_date_1,'г.',''), 'dd.MM.yyyy')),'yyyy-MM-dd'),
                udf_convert_valuedate_to_string(L.slice_date_1)
                )
            ) as eventdate,
            L.inn,
            L.contractor_code,
            L.member_of_special_group,
            L.department,
            L.industry,
            L.slice_date_1,
            L.slice_date_2,
            L.contractor_class,
            L.solvency_group,
            L.points,
            L.credit_limit,
            L.limit_Estimation_RSBU,
            L.fin_Metr_Coverage_Coefficient_Points,
            L.fin_Metr_Hot_Liquidity_Coefficient_Points,
            L.fin_Metr_Capital_Turnover_Points,
            L.fin_Metr_Selling_Profitability_Points,
            L.fin_Metr_Assets_Profitability_Points,
            L.fin_Metr_Financial_Stability_Coefficient_Points,
            L.bus_Rep_Cooperation_Experience_Category,
            L.bus_Rep_Cooperation_Experience_Points,
            L.bus_Rep_Payment_Discipline_Category,
            L.bus_Rep_Payment_Discipline_Points,
            L.calculation_Non_Current_Assets,
            L.calculation_Net_Assets,
            L.calculation_Current_Assets,
            L.calculation_Current_Liabilities,
            R.rsbu_financial_statements,
            R.assets_Non_Current_Intangible_Assets,
            R.assets_Non_Current_RND_Results,
            R.assets_Non_Current_Non_Material_Research_Assets,
            R.assets_Non_Current_Material_Research_Assets,
            R.assets_Non_Current_Fixed_Assets,
            R.assets_Non_Current_IBP_Into_Tangible_Assets,
            R.assets_Non_Current_Financial_Investments,
            R.assets_Non_Current_Deferred_Tax_Asset,
            R.assets_Non_Current_Other_Assets,
            R.assets_Current_Inventory,
            R.assets_Current_VAT_On_Acquired_Valuables,
            R.assets_Current_Receivables,
            R.assets_Current_Long_Term_Receivables,
            R.assets_Currentdebts_Of_Founders,
            R.assets_Current_Financial_Investment,
            R.assets_Current_Cash,
            R.assets_Current_Other,
            R.liability_Equity_Statutory_Capital,
            R.liability_Equity_Own_Stock,
            R.liability_Equity_Non_Current_Assets_Revaluation,
            R.liability_Equity_Equity_Reserve,
            R.liability_Equity_Retained_Earnings,
            R.liability_Long_Term_Liabilities_Loans_And_Borrowings,
            R.liability_Long_Term_Liabilities_Deferred_Tax_Liabilities,
            R.liability_Long_Term_Liabilities_Estimated_Liabilities,
            R.liability_Long_Term_Liabilities_Received_Advances_Payables,
            R.liability_Long_Term_Liabilities_Other_Liabilities,
            R.liability_Short_Term_Liabilities_Loans_And_Borrowings,
            R.liability_Short_Term_Liabilities_Accounts_Payable,
            R.liability_Short_Term_Liabilities_Deferred_Income,
            R.liability_Short_Term_Liabilities_Estimated_Liabilities,
            R.liability_Short_Term_Liabilities_Other_Liabilities,
            R.pnl_Net_Revenue,
            R.pnl_Operating_Profit,
            R.pnl_Year_Net_Profit,
            R.statement_Of_Changes_In_Equity_Net_Assets,
            R.rsbu_financial_statements_currency,
            R.assets_Current_Total,
            R.liability_Short_Term_Liabilities_Total,
            R.liability_Long_Term_Liabilities_Total,
            R.liability_Equity_Total,
            R.assets_Non_Current_Total,
            R.liabilities_Total,
            R.assets_Total,
            R.cover_Ratio,
            R.quick_Liquidity_Ratio,
            R.working_Capital_Turnover,
            R.financial_Stability_Index,
            R.margin_On_Sales,
            R.return_On_Assets
        from {dbSchema}.tmp_flat_rsbu_limit L
        left join {dbSchema}.tmp_flat_rsbu_report R
        ON L.filename = R.filename and L.`year` = R.`year`
    ) res
) T
left join {dbSchema}.md_contractor_custom_dict custom
on T.inn = custom.inn_raw and T.name = custom.name_raw
