select
    r.*,
    coalesce(r.code_md_1, r.code_md_2) as code,
    case when coalesce(r.code_md_1, r.code_md_2) is null then 'NOT_MAPPING' else 'OK' end as error_status,
    "" as sheetName,
    "" as loadDate,
    from_unixtime(unix_timestamp()) as modificationDate
from (
    select
        rsbu.filename,
        rsbu.name_do,
        rsbu.`year`,
        rsbu.name,
        rsbu.eventdate,
        rsbu.inn,
        rsbu.contractor_code,
        rsbu.member_of_special_group,
        rsbu.department,
        rsbu.industry,
        rsbu.slice_date_1,
        rsbu.slice_date_2,
        rsbu.contractor_class,
        rsbu.solvency_group,
        rsbu.points,
        rsbu.credit_limit,
        rsbu.limit_estimation_rsbu,
        rsbu.fin_metr_coverage_coefficient_points,
        rsbu.fin_metr_hot_liquidity_coefficient_points,
        rsbu.fin_metr_capital_turnover_points,
        rsbu.fin_metr_selling_profitability_points,
        rsbu.fin_metr_assets_profitability_points,
        rsbu.fin_metr_financial_stability_coefficient_points,
        rsbu.bus_rep_cooperation_experience_category,
        rsbu.bus_rep_cooperation_experience_points,
        rsbu.bus_rep_payment_discipline_category,
        rsbu.bus_rep_payment_discipline_points,
        rsbu.calculation_non_current_assets,
        rsbu.calculation_net_assets,
        rsbu.calculation_current_assets,
        rsbu.calculation_current_liabilities,
        rsbu.rsbu_financial_statements,
        rsbu.assets_non_current_intangible_assets,
        rsbu.assets_non_current_rnd_results,
        rsbu.assets_non_current_non_material_research_assets,
        rsbu.assets_non_current_material_research_assets,
        rsbu.assets_non_current_fixed_assets,
        rsbu.assets_non_current_ibp_into_tangible_assets,
        rsbu.assets_non_current_financial_investments,
        rsbu.assets_non_current_deferred_tax_asset,
        rsbu.assets_non_current_other_assets,
        rsbu.assets_current_inventory,
        rsbu.assets_current_vat_on_acquired_valuables,
        rsbu.assets_current_receivables,
        rsbu.assets_current_long_term_receivables,
        rsbu.assets_currentdebts_of_founders,
        rsbu.assets_current_financial_investment,
        rsbu.assets_current_cash,
        rsbu.assets_current_other,
        rsbu.liability_equity_statutory_capital,
        rsbu.liability_equity_own_stock,
        rsbu.liability_equity_non_current_assets_revaluation,
        rsbu.liability_equity_equity_reserve,
        rsbu.liability_equity_retained_earnings,
        rsbu.liability_long_term_liabilities_loans_and_borrowings,
        rsbu.liability_long_term_liabilities_deferred_tax_liabilities,
        rsbu.liability_long_term_liabilities_estimated_liabilities,
        rsbu.liability_long_term_liabilities_received_advances_payables,
        rsbu.liability_long_term_liabilities_other_liabilities,
        rsbu.liability_short_term_liabilities_loans_and_borrowings,
        rsbu.liability_short_term_liabilities_accounts_payable,
        rsbu.liability_short_term_liabilities_deferred_income,
        rsbu.liability_short_term_liabilities_estimated_liabilities,
        rsbu.liability_short_term_liabilities_other_liabilities,
        rsbu.pnl_net_revenue,
        rsbu.pnl_operating_profit,
        rsbu.pnl_year_net_profit,
        rsbu.statement_of_changes_in_equity_net_assets,
        rsbu.rsbu_financial_statements_currency,
        rsbu.assets_Current_Total,
        rsbu.liability_Short_Term_Liabilities_Total,
        rsbu.liability_Long_Term_Liabilities_Total,
        rsbu.liability_Equity_Total,
        rsbu.assets_Non_Current_Total,
        rsbu.liabilities_Total,
        rsbu.assets_Total,
        rsbu.cover_Ratio,
        rsbu.quick_Liquidity_Ratio,
        rsbu.working_Capital_Turnover,
        rsbu.financial_Stability_Index,
        rsbu.margin_On_Sales,
        rsbu.return_On_Assets,
        rsbu.id_sha2,
        rsbu.inn_clean,
        rsbu.name_clean,
        rsbu.is_custom_contractor_dict,
      max(md_1.code) as code_md_1,
      max(md_2.code) as code_md_2
    from {dbSchema}.union_flat_rsbu rsbu
    left join (
        select distinct inn_clean, code FROM  {dbSchema}.md_contractor_dict where inn_clean is not null and code is not null
    ) as md_1
    on rsbu.inn_clean = md_1.inn_clean
    left join (
        select distinct name_clean, code FROM  {dbSchema}.md_contractor_dict where inn_clean is null and code is not null
    ) as md_2
    on rsbu.name_clean = md_2.name_clean
    group by
        rsbu.filename,
        rsbu.name_do,
        rsbu.`year`,
        rsbu.name,
        rsbu.eventdate,
        rsbu.inn,
        rsbu.contractor_code,
        rsbu.member_of_special_group,
        rsbu.department,
        rsbu.industry,
        rsbu.slice_date_1,
        rsbu.slice_date_2,
        rsbu.contractor_class,
        rsbu.solvency_group,
        rsbu.points,
        rsbu.credit_limit,
        rsbu.limit_estimation_rsbu,
        rsbu.fin_metr_coverage_coefficient_points,
        rsbu.fin_metr_hot_liquidity_coefficient_points,
        rsbu.fin_metr_capital_turnover_points,
        rsbu.fin_metr_selling_profitability_points,
        rsbu.fin_metr_assets_profitability_points,
        rsbu.fin_metr_financial_stability_coefficient_points,
        rsbu.bus_rep_cooperation_experience_category,
        rsbu.bus_rep_cooperation_experience_points,
        rsbu.bus_rep_payment_discipline_category,
        rsbu.bus_rep_payment_discipline_points,
        rsbu.calculation_non_current_assets,
        rsbu.calculation_net_assets,
        rsbu.calculation_current_assets,
        rsbu.calculation_current_liabilities,
        rsbu.rsbu_financial_statements,
        rsbu.assets_non_current_intangible_assets,
        rsbu.assets_non_current_rnd_results,
        rsbu.assets_non_current_non_material_research_assets,
        rsbu.assets_non_current_material_research_assets,
        rsbu.assets_non_current_fixed_assets,
        rsbu.assets_non_current_ibp_into_tangible_assets,
        rsbu.assets_non_current_financial_investments,
        rsbu.assets_non_current_deferred_tax_asset,
        rsbu.assets_non_current_other_assets,
        rsbu.assets_current_inventory,
        rsbu.assets_current_vat_on_acquired_valuables,
        rsbu.assets_current_receivables,
        rsbu.assets_current_long_term_receivables,
        rsbu.assets_currentdebts_of_founders,
        rsbu.assets_current_financial_investment,
        rsbu.assets_current_cash,
        rsbu.assets_current_other,
        rsbu.liability_equity_statutory_capital,
        rsbu.liability_equity_own_stock,
        rsbu.liability_equity_non_current_assets_revaluation,
        rsbu.liability_equity_equity_reserve,
        rsbu.liability_equity_retained_earnings,
        rsbu.liability_long_term_liabilities_loans_and_borrowings,
        rsbu.liability_long_term_liabilities_deferred_tax_liabilities,
        rsbu.liability_long_term_liabilities_estimated_liabilities,
        rsbu.liability_long_term_liabilities_received_advances_payables,
        rsbu.liability_long_term_liabilities_other_liabilities,
        rsbu.liability_short_term_liabilities_loans_and_borrowings,
        rsbu.liability_short_term_liabilities_accounts_payable,
        rsbu.liability_short_term_liabilities_deferred_income,
        rsbu.liability_short_term_liabilities_estimated_liabilities,
        rsbu.liability_short_term_liabilities_other_liabilities,
        rsbu.pnl_net_revenue,
        rsbu.pnl_operating_profit,
        rsbu.pnl_year_net_profit,
        rsbu.statement_of_changes_in_equity_net_assets,
        rsbu.rsbu_financial_statements_currency,
        rsbu.assets_Current_Total,
        rsbu.liability_Short_Term_Liabilities_Total,
        rsbu.liability_Long_Term_Liabilities_Total,
        rsbu.liability_Equity_Total,
        rsbu.assets_Non_Current_Total,
        rsbu.liabilities_Total,
        rsbu.assets_Total,
        rsbu.cover_Ratio,
        rsbu.quick_Liquidity_Ratio,
        rsbu.working_Capital_Turnover,
        rsbu.financial_Stability_Index,
        rsbu.margin_On_Sales,
        rsbu.return_On_Assets,
        rsbu.id_sha2,
        rsbu.inn_clean,
        rsbu.name_clean,
        rsbu.is_custom_contractor_dict
) r
