select distinct
r.filename,
r.code,
r.name_do,
r.`year`,
r.name,
r.name_clean as norm_name,
r.eventdate,
r.inn,
r.inn_clean,
r.is_custom_contractor_dict,
r.contractor_code,
r.member_of_special_group,
r.department,
r.industry,
r.slice_date_1,
r.slice_date_2,
CASE
    WHEN trim(r.contractor_class) IN ('a', 'A', 'а', 'А') THEN 'A'
    WHEN trim(r.contractor_class) IN ('b', 'B', 'в', 'В') THEN 'B'
    WHEN trim(r.contractor_class) IN ('c', 'C', 'с', 'С') THEN 'C'
    ELSE null
    END AS contractor_class,
r.solvency_group,
r.points,
r.credit_limit,
udf_convert_to_local_date(coalesce(
    from_unixtime(unix_timestamp(r.limit_estimation_rsbu, 'MM/dd/yy'), 'yyyy-MM-dd'),
    from_unixtime(unix_timestamp(r.limit_estimation_rsbu, 'dd.MM.yyyy'), 'yyyy-MM-dd'),
    udf_convert_valuedate_to_string(r.limit_estimation_rsbu)
    )) as limit_estimation_rsbu,
r.fin_metr_coverage_coefficient_points,
r.fin_metr_hot_liquidity_coefficient_points,
r.fin_metr_capital_turnover_points,
r.fin_metr_selling_profitability_points,
r.fin_metr_assets_profitability_points,
r.fin_metr_financial_stability_coefficient_points,
r.bus_Rep_Cooperation_Experience_Category,
r.bus_Rep_Cooperation_Experience_Points,
r.bus_Rep_Payment_Discipline_Category,
r.bus_Rep_Payment_Discipline_Points,
r.calculation_non_current_assets,
r.calculation_net_assets,
r.calculation_current_assets,
r.calculation_current_liabilities,
r.rsbu_financial_statements,
r.assets_non_current_intangible_assets,
r.assets_non_current_rnd_results,
r.assets_non_current_non_material_research_assets,
r.assets_non_current_material_research_assets,
r.assets_non_current_fixed_assets,
r.assets_non_current_ibp_into_tangible_assets,
r.assets_non_current_financial_investments,
r.assets_non_current_deferred_tax_asset,
r.assets_non_current_other_assets,
r.assets_current_inventory,
r.assets_current_vat_on_acquired_valuables,
r.assets_current_receivables,
r.assets_current_long_term_receivables,
r.assets_currentdebts_of_founders,
r.assets_current_financial_investment,
r.assets_current_cash,
r.assets_current_other,
r.liability_equity_statutory_capital,
r.liability_equity_own_stock,
r.liability_equity_non_current_assets_revaluation,
r.liability_equity_equity_reserve,
r.liability_equity_retained_earnings,
r.liability_long_term_liabilities_loans_and_borrowings,
r.liability_long_term_liabilities_deferred_tax_liabilities,
r.liability_long_term_liabilities_estimated_liabilities,
r.liability_long_term_liabilities_received_advances_payables,
r.liability_long_term_liabilities_other_liabilities,
r.liability_short_term_liabilities_loans_and_borrowings,
r.liability_short_term_liabilities_accounts_payable,
r.liability_short_term_liabilities_deferred_income,
r.liability_short_term_liabilities_estimated_liabilities,
r.liability_short_term_liabilities_other_liabilities,
r.pnl_net_revenue,
r.pnl_operating_profit,
r.pnl_year_net_profit,
r.statement_of_changes_in_equity_net_assets,
r.rsbu_financial_statements_currency,
r.error_status,
r.sheetname,
r.loaddate,
r.modificationdate,
r.assets_Current_Total,
r.liability_Short_Term_Liabilities_Total,
r.liability_Long_Term_Liabilities_Total,
r.liability_Equity_Total,
r.assets_Non_Current_Total,
r.liabilities_Total,
r.assets_Total,
r.cover_Ratio,
r.quick_Liquidity_Ratio,
r.working_Capital_Turnover,
r.financial_Stability_Index,
r.margin_On_Sales,
r.return_On_Assets,
r.id_sha2
from {dbSchema}.collisions_report_express_analysis r
WHERE r.error_status = 'OK'
ORDER BY r.code, r.`year`
